CPP=ccache g++ 
CC=ccache gcc
CFLAGS=-Wall -Werror -g
LINKS	= -lpthread -lrt -lev -lglog -lmysqlcppconn -llua5.2 -lgtest

OBJS	= twomapT_unittest.o \
		  PoolT_unittest.o \
		  libev_unittest.o \
		  database_unittest.o \
          ../ThreadPool.o \
		  ../ProcessManager.o \
		  ../Single.o \
		  ../Sock.o \
		  ../Evloop.o \
		  ../RecvTask.o \
		  ../SendTask.o \
		  ../database.o \
		  ../Config.o \
		  gtest_main.o
#Evloop_unittest.o \

EXE=test.out

VPATH		 = ./../

INC=-I.\
	-I./../ \
	-I$(HOME)/Downloads/gtest-1.6.0/include

LIB=-L.\
	-L./../ \
	-L$(HOME)/Downloads/gtest-1.6.0/lib/.libs

all:clean $(EXE)

$(EXE):$(OBJS)
		 $(CPP) $(CFLAGS) $(LIB) $(OBJS) -o $@ $(LINKS)

%.o:%.cc
		 $(CPP) $(CFLAGS) $(INC) -c $< -o $@

%.o:%.cpp
		 $(CPP) $(CFLAGS) $(INC) -c $< -o $@

%.o:%.c
		 $(CC) $(CFLAGS) $(INC) -c $< -o $@

clean:
	rm -rf $(OBJS) 
	rm -rf $(EXE) 
	rm -rf core*
	rm -rf logs
	rm -f .lock
